server:
  port: 6565
spring:
  datasource:
    url: jdbc:postgresql://twistways.com:5432/flippermods
    username: flipper
    password: das Flipper passwort1 1 elf
  jpa:
    hibernate:
      ddl-auto: update

